### ISSUE TITLE
Export filenames using WordPress locales

### ISSUE THREAD

**Issue by DavidAnderson684** [toolstack/gp-bulk-download-translations#1]
Hi Greg,

Thanks for this great plugin. I've just moved an old GP install over to GP-as-a-plugin, and installed this bulk-download-translations plugin.

Before, I was using a custom script, which saved filenames based on the WP locale (since, I'm using GP to translate WP plugins). The bulk exporter doesn't have an option for this. It'd be great if it did.

I don't know much about GP's internals, but, in case it helps... my old script (which I can hardly remember what it's doing), gets the WP locales with a fragment like this:

$locales = (new GP_Locales)->locales;
// Then for each file to be output:
$output_basename = $project_path.'-'.$locales[$locale]->wp_locale.'.mo';

David

**Comment by toolstack** [comment]
It's not really the bulk exporters job to handle the filenames, even if you download the exports one at a time you have this problem.

That's why I wrote the [GP Use Slug for Downloads](https://github.com/toolstack/gp-use-slug-for-downloads) plugin :wink:.

**Comment by DavidAnderson684** [comment]
Hi,

Thanks. It looks like I can investigate the source of that to try to work out what needs doing. (I don't want to use the slug as the filename; but, the hooks in there are presusumably the ones to investigate).

David

**Comment by toolstack** [comment]
Yes, the hooks are there.

I set my slug to be the filename I want for a given translation set, that let's me control the filename that is used on a per project basis.

But if you can use the same hooks to do whatever you want with the filename before it is exported.

**Comment by DavidAnderson684** [comment]
Here's the code, in case anyone else is interested:

```
        add_action( 'gp_export_translations_filename', 'my_gp_export_translations_filename', 10, 5 );
        function my_gp_export_translations_filename( $filename, $format, $locale, $project, $translation_set ) {
                if( $translation_set->slug != '' && $translation_set->slug != 'default' && !empty($locale->wp_locale) ) {
                        $filename = sprintf( $format->filename_pattern . '.' . $format->extension, str_replace( '/', '-', $project->path ), $locale->wp_locale);
                }

                return $filename;
        }
```
